---
version: "2"
services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud_with_OnlyOffice
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_HOST=nextcloud_db
      - NEXTCLOUD_DATA_DIR=/All_Data
    volumes:
      - ${app_data}/appdata:/var/www/html
      - ${data}:/All_Data
    ports:
      - ${PORT}:80
    restart: unless-stopped
    depends_on:
      - nextcloud_db
  nextcloud_db:
    image: postgres:alpine
    container_name: nextcloud_db
    hostname: nextcloud_db
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - POSTGRES_DB=nextcloud_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ${app_data}/db:/var/lib/postgresql/data
    restart: unless-stopped
  onlyoffice:
    image: onlyoffice/documentserver
    container_name: onlyoffice
    expose:
      - '80'
      - '443'
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DB_TYPE=postgres
      - DB_PWD=${DATABASE_PASSWORD}
      - DB_HOST=nextcloud_db
      - DB_NAME=nextcloud
      - DB_USER=postgres
    volumes:
      - ${app_data}/officeData:/var/www/onlyoffice/Data
      - ${app_data}/officeLog:/var/log/onlyoffice
    restart: unless-stopped
