---
version: "2"
services:
  nextcloud:
    image: nextcloud:fpm
    container_name: nextcloud_with_OnlyOffice
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - POSTGRES_DB=nextcloud_db
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_HOST=nextcloud_db
      - NEXTCLOUD_DATA_DIR=/All_Data
    volumes:
      - ${app_data}:/var/www/html
      - ${data}:/All_Data
    expose:
      - '9000'
      - '80'
    restart: unless-stopped
    depends_on:
      - nextcloud_db
  nextcloud_db:
    image: postgres:alpine
    container_name: nextcloud_db
    hostname: nextcloud_db
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - POSTGRES_DB=nextcloud_db
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ${db_data}:/var/lib/postgresql/data
    restart: unless-stopped
  nginx:
    container_name: nextcloud-nginx-server
    image: nginx
    restart: always
    ports:
      - ${PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d:ro
      - ${app_data}:/var/www/html
    volumes_from:
      - nextcloud
  onlyoffice:
    image: onlyoffice/documentserver
    container_name: onlyoffice
    expose:
      - '80'
      - '443'
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DB_TYPE=postgres
      - DB_PWD=${DATABASE_PASSWORD}
      - DB_HOST=nextcloud_db
      - DB_NAME=nextcloud_db
    volumes:
      - ${document_data}:/var/www/onlyoffice/Data
      - ${document_log}:/var/log/onlyoffice
    restart: unless-stopped
